// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type VerifyReq struct {
	Token string `json:"token"`
}

type VerifyResp struct {
	Valid   bool   `json:"valid"`
	UserID  int64  `json:"user_id.optional"`
	Message string `json:"message.optional"`
}
