// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user-rpc.proto

package userrpcclient

import (
	"context"

	"user-rpc/userrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUserReq  = userrpc.CreateUserReq
	CreateUserResp = userrpc.CreateUserResp
	GetUserReq     = userrpc.GetUserReq
	GetUserResp    = userrpc.GetUserResp
	Request        = userrpc.Request
	Response       = userrpc.Response
	User           = userrpc.User

	UserRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

func (m *defaultUserRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := userrpc.NewUserRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultUserRpc) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := userrpc.NewUserRpcClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUserRpc) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	client := userrpc.NewUserRpcClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}
