// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user-rpc.proto

package userrpcclient

import (
	"context"

	"user-rpc/userrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = userrpc.Request
	Response = userrpc.Response

	UserRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

func (m *defaultUserRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := userrpc.NewUserRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
