// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateUserReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type GetUserReq struct {
	ID int64 `path:"id"`
}

type UserResp struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
