// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user-rpc.proto

package server

import (
	"context"

	"go-zero-learning/service/user/user-rpc/internal/logic"
	"go-zero-learning/service/user/user-rpc/internal/svc"
	"go-zero-learning/service/user/user-rpc/userrpc"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
	userrpc.UnimplementedUserRpcServer
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) Ping(ctx context.Context, in *userrpc.Request) (*userrpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// 根据 ID 查询用户基本信息（不返回密码）
func (s *UserRpcServer) GetUser(ctx context.Context, in *userrpc.GetUserReq) (*userrpc.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// 用户列表（分页，支持 keyword 搜索）
func (s *UserRpcServer) ListUsers(ctx context.Context, in *userrpc.ListUsersReq) (*userrpc.ListUsersResp, error) {
	l := logic.NewListUsersLogic(ctx, s.svcCtx)
	return l.ListUsers(in)
}

// 创建用户
func (s *UserRpcServer) CreateUser(ctx context.Context, in *userrpc.CreateUserReq) (*userrpc.CreateUserResp, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}
