// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user-rpc.proto

package server

import (
	"context"

	"user-rpc/internal/logic"
	"user-rpc/internal/svc"
	"user-rpc/userrpc"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
	userrpc.UnimplementedUserRpcServer
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) Ping(ctx context.Context, in *userrpc.Request) (*userrpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserRpcServer) GetUser(ctx context.Context, in *userrpc.GetUserReq) (*userrpc.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserRpcServer) CreateUser(ctx context.Context, in *userrpc.CreateUserReq) (*userrpc.CreateUserResp, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}
