// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetUserInfoReq struct {
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string       `json:"token"`
	UserInfo UserInfoResp `json:"user_info"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserInfoResp struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
