// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetUserInfoReq struct {
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string       `json:"token"`
	UserInfo UserInfoResp `json:"user_info"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserInfoResp struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type GetUserListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"page_size,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type GetUserListResp struct {
	Users    []UserInfoResp `json:"users"`
	Total    int64          `json:"total"`
	Page     int64          `json:"page"`
	PageSize int64          `json:"page_size"`
}

type UpdateUserReq struct {
	Email    string `json:"email,optional"`
	Password string `json:"password,optional"`
}
