// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AssignRolePermissionReq struct {
	RoleID       int64 `path:"id"`            // 角色ID(路径参数)
	PermissionID int64 `json:"permission_id"` // 权限ID(请求体)
}

type AssignRolePermissionResp struct {
	Message string `json:"message"`
}

type AssignUserRoleReq struct {
	UserID int64 `path:"id"`      // 用户ID(路径参数)
	RoleID int64 `json:"role_id"` // 角色ID(请求体)
}

type AssignUserRoleResp struct {
	Message string `json:"message"`
}

type CreateMenuReq struct {
	Name     string `json:"name"`
	Code     string `json:"code"`
	Desc     string `json:"desc,omitempty"`
	ParentID int64  `json:"parent_id,omitempty"`
	Path     string `json:"path,omitempty"`
	Icon     string `json:"icon,omitempty"`
	Type     int    `json:"type"`
	Sort     int    `json:"sort,omitempty"`
	Status   int    `json:"status,omitempty"` // 默认在逻辑层处理
}

type CreatePermissionReq struct {
	Name string `json:"name"`
	Code string `json:"code"`
	Desc string `json:"desc,omitempty"`
}

type CreateRoleReq struct {
	Name string `json:"name"`
	Code string `json:"code"`
	Desc string `json:"desc,omitempty"`
}

type DeleteMenuReq struct {
	ID int64 `path:"id"`
}

type DeleteMenuResp struct {
	Message string `json:"message"`
}

type DeletePermissionReq struct {
	ID int64 `path:"id"`
}

type DeletePermissionResp struct {
	Message string `json:"message"`
}

type DeleteRoleReq struct {
	ID int64 `path:"id"`
}

type DeleteRoleResp struct {
	Message string `json:"message"`
}

type DeleteUserReq struct {
	ID int64 `path:"id"`
}

type DeleteUserResp struct {
	Message string `json:"message"`
}

type GetMenuDetailReq struct {
	ID int64 `path:"id"`
}

type GetMenuListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"page_size,default=10"`
	Keyword  string `form:"keyword,optional"`
	All      bool   `form:"all,optional"` // 是否获取全部（不分页），用于树形结构
}

type GetMenuListResp struct {
	Menus    []MenuInfoResp `json:"menus"`
	Total    int64          `json:"total"`
	Page     int64          `json:"page"`
	PageSize int64          `json:"page_size"`
}

type GetPermissionDetailReq struct {
	ID int64 `path:"id"`
}

type GetPermissionListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"page_size,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type GetPermissionListResp struct {
	Permissions []PermissionInfoResp `json:"permissions"`
	Total       int64                `json:"total"`
	Page        int64                `json:"page"`
	PageSize    int64                `json:"page_size"`
}

type GetRoleDetailReq struct {
	ID int64 `path:"id"`
}

type GetRoleListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"page_size,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type GetRoleListResp struct {
	Roles    []RoleInfoResp `json:"roles"`
	Total    int64          `json:"total"`
	Page     int64          `json:"page"`
	PageSize int64          `json:"page_size"`
}

type GetRolePermissionListReq struct {
	RoleID int64 `path:"id"` // 角色ID(路径参数)
}

type GetRolePermissionListResp struct {
	Permissions []PermissionInfoResp `json:"permissions"`
}

type GetUserDetailReq struct {
	ID int64 `path:"id"` // 路径参数：用户ID
}

type GetUserInfoReq struct {
}

type GetUserListReq struct {
	Page     int64  `form:"page,default=1"`       // 页码，默认第1页
	PageSize int64  `form:"page_size,default=10"` // 每页数量，默认10条
	Keyword  string `form:"keyword,optional"`     // 搜索关键词（用户名或邮箱），可选
}

type GetUserListResp struct {
	Users    []UserInfoResp `json:"users"`
	Total    int64          `json:"total"`     // 总用户数
	Page     int64          `json:"page"`      // 当前页码
	PageSize int64          `json:"page_size"` // 每页数量
}

type GetUserRolesReq struct {
	UserID int64 `path:"id"` // 用户ID(路径参数)
}

type GetUserRolesResp struct {
	Roles []RoleInfoResp `json:"roles"` // 角色列表
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string       `json:"token"`
	UserInfo UserInfoResp `json:"user_info"`
}

type MenuInfoResp struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Desc      string `json:"desc"`
	ParentID  int64  `json:"parent_id"`
	Path      string `json:"path"`
	Icon      string `json:"icon"`
	Type      int    `json:"type"`
	Sort      int    `json:"sort"`
	Status    int    `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type PermissionInfoResp struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Desc      string `json:"desc"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RemoveRolePermissionReq struct {
	RoleID       int64 `path:"id"`            // 角色ID(路径参数)
	PermissionID int64 `path:"permission_id"` // 权限ID(路径参数)
}

type RemoveRolePermissionResp struct {
	Message string `json:"message"`
}

type RemoveUserRoleReq struct {
	UserID int64 `path:"id"`      // 用户ID(路径参数)
	RoleID int64 `path:"role_id"` // 角色ID(路径参数)
}

type RemoveUserRoleResp struct {
	Message string `json:"message"`
}

type RoleInfoResp struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Desc      string `json:"desc"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UpdateMenuReq struct {
	ID       int64   `path:"id"`
	Name     *string `json:"name,omitempty"`
	Code     *string `json:"code,omitempty"`
	Desc     *string `json:"desc,omitempty"`
	ParentID int64   `json:"parent_id"`
	Path     *string `json:"path,omitempty"`
	Icon     *string `json:"icon,omitempty"`
	Type     *int    `json:"type,omitempty"`
	Sort     *int    `json:"sort,omitempty"`
	Status   *int    `json:"status,omitempty"`
}

type UpdatePermissionReq struct {
	ID   int64   `path:"id"`
	Name *string `json:"name,omitempty"`
	Code *string `json:"code,omitempty"`
	Desc *string `json:"desc,omitempty"`
}

type UpdateRoleReq struct {
	ID   int64   `path:"id"`             // 路径参数：角色ID
	Name *string `json:"name,omitempty"` // 角色名称（可选）
	Code *string `json:"code,omitempty"` // 角色代码（可选）
	Desc *string `json:"desc,omitempty"` // 角色描述（可选）
}

type UpdateUserDetailReq struct {
	ID       int64   `path:"id"`                 // 路径参数：用户ID
	Email    *string `json:"email,omitempty"`    // 邮箱（可选）
	Password *string `json:"password,omitempty"` // 密码（可选）
}

type UpdateUserReq struct {
	Email    *string `json:"email,omitempty"`    // 邮箱（可选）
	Password *string `json:"password,omitempty"` // 密码（可选）
}

type UserInfoResp struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type CreateProductReq struct {
	Name        string `json:"name" validate:"required,max=100"`
	Description string `json:"description,omitempty"`
	Price       int64  `json:"price" validate:"required,min=1,max=99999900"`
	Status      *int   `json:"status,omitempty" validate:"omitempty,oneof 0 1"`
}

type DeleteProductReq struct {
	ID int64 `path:"id"`
}

type DeleteProductResp struct {
	Message string `json:"message"`
}

type GetProductDetailReq struct {
	ID int64 `path:"id"`
}

type GetProductListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"page_size,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type GetProductListResp struct {
	Products []ProductInfoResp `json:"products"`
	Page     int64             `json:"page"`
	PageSize int64             `json:"page_size"`
	Total    int64             `json:"total"`
}

type ProductInfoResp struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
	Status      int    `json:"status"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type UpdateProductReq struct {
	ID          int64   `path:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Price       *int64  `json:"price,omitempty"`
	Status      *int    `json:"status,omitempty"`
}

type UpdateProductStatusReq struct {
	ID     int64 `path:"id"`
	Status int   `json:"status" validate:"oneof 0 1"`
}

type UpdateProductStatusResp struct {
	Message string `json:"message"`
}

type CreateOrderItem struct {
	ProductID int64 `json:"product_id"` // 商品ID
	Quantity  int   `json:"quantity"`   // 购买数量
}

type CreateOrderReq struct {
	Items  []CreateOrderItem `json:"items"`            // 商品列表
	Remark string            `json:"remark,omitempty"` // 订单备注（可选）
}

type CreateOrderResp struct {
	ID          int64           `json:"id"`
	OrderNo     string          `json:"order_no"`
	UserID      int64           `json:"user_id"`
	TotalAmount int64           `json:"total_amount"` // 总金额（分）
	Status      int             `json:"status"`
	StatusText  string          `json:"status_text"`
	Remark      string          `json:"remark"`
	Items       []OrderItemResp `json:"items"` // 订单项列表
	CreatedAt   int64           `json:"created_at"`
}

type GetOrderDetailReq struct {
	ID int64 `path:"id"`
}

type GetOrderListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"page_size,default=10"`
	Status   int    `form:"status,optional"`  // 按状态筛选
	Keyword  string `form:"keyword,optional"` // 搜索关键词（订单编号）
}

type GetOrderListResp struct {
	Orders   []OrderInfoResp `json:"orders"`
	Total    int64           `json:"total"`
	Page     int64           `json:"page"`
	PageSize int64           `json:"page_size"`
}

type OrderInfoResp struct {
	ID          int64           `json:"id"`
	OrderNo     string          `json:"order_no"`
	UserID      int64           `json:"user_id"`
	TotalAmount int64           `json:"total_amount"`
	Status      int             `json:"status"`
	StatusText  string          `json:"status_text"`
	Remark      string          `json:"remark"`
	Items       []OrderItemResp `json:"items,omitempty"` // 订单项（详情时返回）
	CreatedAt   int64           `json:"created_at"`
	UpdatedAt   int64           `json:"updated_at"`
}

type OrderItemResp struct {
	ID          int64  `json:"id"`
	ProductID   int64  `json:"product_id"`
	ProductName string `json:"product_name"`
	ProductDesc string `json:"product_desc"`
	Price       int64  `json:"price"`    // 单价（分）
	Quantity    int    `json:"quantity"` // 数量
	Amount      int64  `json:"amount"`   // 小计（分）
}

type UpdateOrderStatusReq struct {
	ID     int64 `path:"id"`
	Status int   `json:"status"`
}

type CategoryInfoResp struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Desc      string `json:"desc"`
	ParentID  int64  `json:"parent_id"`
	Sort      int    `json:"sort"`
	Status    int    `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type CreateCategoryReq struct {
	Name     string `json:"name"`
	Desc     string `json:"desc,omitempty"`
	ParentID int64  `json:"parent_id,omitempty"`
	Sort     int    `json:"sort,omitempty"`
	Status   *int   `json:"status,omitempty"`
}

type DeleteCategoryReq struct {
	ID int64 `path:"id"`
}

type DeleteCategoryResp struct {
	Message string `json:"message"`
}

type GetCategoryDetailReq struct {
	ID int64 `path:"id"`
}

type GetCategoryListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"page_size,default=10"`
	Keyword  string `form:"keyword,optional"`
	All      bool   `form:"all,optional"` // 是否获取全部（不分页），用于树形结构
}

type GetCategoryListResp struct {
	Categories []CategoryInfoResp `json:"categories"`
	Total      int64              `json:"total"`
	Page       int64              `json:"page"`
	PageSize   int64              `json:"page_size"`
}

type UpdateCategoryReq struct {
	ID       int64   `path:"id"`
	Name     *string `json:"name,omitempty"`
	Desc     *string `json:"desc,omitempty"`
	ParentID *int64  `json:"parent_id,omitempty"`
	Sort     *int    `json:"sort,omitempty"`
	Status   *int    `json:"status,omitempty"`
}

type AddCartItemReq struct {
	ProductID int64 `json:"product_id"` // 商品ID
	Quantity  int   `json:"quantity"`   // 购买数量
}

type CartItemResp struct {
	ID          int64  `json:"id"`
	ProductID   int64  `json:"product_id"`
	ProductName string `json:"product_name"`
	Price       int64  `json:"price"`    // 单价（分）
	Quantity    int    `json:"quantity"` // 数量
	Amount      int64  `json:"amount"`   // 小计（分）
}

type ClearCartReq struct {
}

type ClearCartResp struct {
	Message string `json:"message"`
}

type DeleteCartItemReq struct {
	ItemID int64 `path:"item_id"` // 购物车项ID（路径参数）
}

type DeleteCartItemResp struct {
	Message string `json:"message"`
}

type GetCartReq struct {
}

type GetCartResp struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Items       []CartItemResp `json:"items"`        // 购物车项列表
	TotalAmount int64          `json:"total_amount"` // 总金额（分）
	ItemCount   int            `json:"item_count"`   // 商品种类数量
}

type UpdateCartItemReq struct {
	ItemID   int64 `path:"item_id"`  // 购物车项ID（路径参数）
	Quantity int   `json:"quantity"` // 新数量
}
