// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"go-zero-learning/common/middleware"
	"go-zero-learning/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 创建认证中间件
	authMiddleware := middleware.NewAuthMiddleware(serverCtx.JWT)

	// 不需要认证的路由
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/users/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/users",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	// 需要认证的路由（应用认证中间件）
	authRoutes := rest.WithMiddlewares(
		[]rest.Middleware{authMiddleware.Handle},
		rest.Route{
			Method:  http.MethodGet,
			Path:    "/api/users/me",
			Handler: GetUserInfoHandler(serverCtx),
		},
		rest.Route{
			Method:  http.MethodGet,
			Path:    "/api/users",
			Handler: GetUserListHandler(serverCtx),
		},
		rest.Route{
			Method:  http.MethodGet,
			Path:    "/api/users/:id",
			Handler: GetUserDetailHandler(serverCtx),
		},
		rest.Route{
			Method:  http.MethodPut,
			Path:    "/api/users/me",
			Handler: UpdateUserHandler(serverCtx),
		},
		rest.Route{
			Method:  http.MethodDelete,
			Path:    "/api/users/:id",
			Handler: DeleteUserHandler(serverCtx),
		},
	)

	server.AddRoutes(authRoutes)
}
