// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"go-zero-learning/common/middleware"
	"go-zero-learning/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 创建权限中间件
	authMiddleware := middleware.NewAuthMiddleware(serverCtx.JWT)
	// 创建日志中间件
	loggingMiddleware := middleware.NewLoggingMiddleware()

	// 不需要认证的路由
	server.AddRoutes(
		rest.WithMiddleware(
			loggingMiddleware.Handle, // 应用日志中间件
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/users/login",
				Handler: LoginHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/users",
				Handler: RegisterHandler(serverCtx),
			},
		),
	)

	// 需要认证的路由（应用认证和日志中间件）
	authRoutes := rest.WithMiddlewares(
		[]rest.Middleware{
			authMiddleware.Handle,    // 认证中间件
			loggingMiddleware.Handle, // 日志中间件
		},
		rest.Route{
			Method:  http.MethodGet,
			Path:    "/api/users/me",
			Handler: GetUserInfoHandler(serverCtx),
		},
		rest.Route{
			Method:  http.MethodGet,
			Path:    "/api/users",
			Handler: GetUserListHandler(serverCtx),
		},
		rest.Route{
			Method:  http.MethodGet,
			Path:    "/api/users/:id",
			Handler: GetUserDetailHandler(serverCtx),
		},
		rest.Route{
			Method:  http.MethodPut,
			Path:    "/api/users/me",
			Handler: UpdateUserHandler(serverCtx),
		},
		rest.Route{
			Method: http.MethodPut,
			// 注意顺序，要放到/me下面;如果放到/me上，/me无法处理了
			Path:    "/api/users/:id",
			Handler: UpdateUserDetailHandler(serverCtx),
		},
		rest.Route{
			Method:  http.MethodDelete,
			Path:    "/api/users/:id",
			Handler: DeleteUserHandler(serverCtx),
		},
	)

	server.AddRoutes(authRoutes)
}
