// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product-rpc.proto

package server

import (
	"context"

	"go-zero-learning/service/product/product-rpc/internal/logic"
	"go-zero-learning/service/product/product-rpc/internal/svc"
	"go-zero-learning/service/product/product-rpc/productrpc"
)

type ProductRpcServer struct {
	svcCtx *svc.ServiceContext
	productrpc.UnimplementedProductRpcServer
}

func NewProductRpcServer(svcCtx *svc.ServiceContext) *ProductRpcServer {
	return &ProductRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductRpcServer) Ping(ctx context.Context, in *productrpc.Request) (*productrpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// 根据 ID 查询商品详情
func (s *ProductRpcServer) GetProduct(ctx context.Context, in *productrpc.GetProductReq) (*productrpc.GetProductResp, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

// 商品列表（分页，支持 keyword 搜索）
func (s *ProductRpcServer) ListProducts(ctx context.Context, in *productrpc.ListProductReq) (*productrpc.ListProductResp, error) {
	l := logic.NewListProductsLogic(ctx, s.svcCtx)
	return l.ListProducts(in)
}

// 创建商品
func (s *ProductRpcServer) CreateProduct(ctx context.Context, in *productrpc.CreateProductReq) (*productrpc.CreateProductResp, error) {
	l := logic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

// 更新商品
func (s *ProductRpcServer) UpdateProduct(ctx context.Context, in *productrpc.UpdateProductReq) (*productrpc.UpdateProductResp, error) {
	l := logic.NewUpdateProductLogic(ctx, s.svcCtx)
	return l.UpdateProduct(in)
}

// 更新商品状态
func (s *ProductRpcServer) UpdateProductStatus(ctx context.Context, in *productrpc.UpdateProductStatusReq) (*productrpc.UpdateProductStatusResp, error) {
	l := logic.NewUpdateProductStatusLogic(ctx, s.svcCtx)
	return l.UpdateProductStatus(in)
}

// 删除商品
func (s *ProductRpcServer) DeleteProduct(ctx context.Context, in *productrpc.DeleteProductReq) (*productrpc.DeleteProductResp, error) {
	l := logic.NewDeleteProductLogic(ctx, s.svcCtx)
	return l.DeleteProduct(in)
}
