// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user-rpc.proto

package userrpcclient

import (
	"context"

	"go-zero-learning/service/user/user-rpc/userrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserReq    = userrpc.GetUserReq
	GetUserResp   = userrpc.GetUserResp
	ListUsersReq  = userrpc.ListUsersReq
	ListUsersResp = userrpc.ListUsersResp
	Request       = userrpc.Request
	Response      = userrpc.Response
	UserItem      = userrpc.UserItem

	UserRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		// 根据 ID 查询用户基本信息（不返回密码）
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		// 用户列表（分页， 无搜索条件）
		ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

func (m *defaultUserRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := userrpc.NewUserRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// 根据 ID 查询用户基本信息（不返回密码）
func (m *defaultUserRpc) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := userrpc.NewUserRpcClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

// 用户列表（分页， 无搜索条件）
func (m *defaultUserRpc) ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error) {
	client := userrpc.NewUserRpcClient(m.cli.Conn())
	return client.ListUsers(ctx, in, opts...)
}
