// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product-rpc.proto

package productrpcclient

import (
	"context"

	"go-zero-learning/service/product/product-rpc/productrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetProductReq  = productrpc.GetProductReq
	GetProductResp = productrpc.GetProductResp
	Request        = productrpc.Request
	Response       = productrpc.Response

	ProductRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		// 根据 ID 查询商品详情
		GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
	}

	defaultProductRpc struct {
		cli zrpc.Client
	}
)

func NewProductRpc(cli zrpc.Client) ProductRpc {
	return &defaultProductRpc{
		cli: cli,
	}
}

func (m *defaultProductRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := productrpc.NewProductRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// 根据 ID 查询商品详情
func (m *defaultProductRpc) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	client := productrpc.NewProductRpcClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}
