// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product-rpc.proto

package productrpcclient

import (
	"context"

	"go-zero-learning/service/product/product-rpc/productrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateProductReq        = productrpc.CreateProductReq
	CreateProductResp       = productrpc.CreateProductResp
	DeleteProductReq        = productrpc.DeleteProductReq
	DeleteProductResp       = productrpc.DeleteProductResp
	GetProductReq           = productrpc.GetProductReq
	GetProductResp          = productrpc.GetProductResp
	ListProductReq          = productrpc.ListProductReq
	ListProductResp         = productrpc.ListProductResp
	ProductItem             = productrpc.ProductItem
	Request                 = productrpc.Request
	Response                = productrpc.Response
	UpdateProductReq        = productrpc.UpdateProductReq
	UpdateProductResp       = productrpc.UpdateProductResp
	UpdateProductStatusReq  = productrpc.UpdateProductStatusReq
	UpdateProductStatusResp = productrpc.UpdateProductStatusResp

	ProductRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		// 根据 ID 查询商品详情
		GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
		// 商品列表（分页，支持 keyword 搜索）
		ListProducts(ctx context.Context, in *ListProductReq, opts ...grpc.CallOption) (*ListProductResp, error)
		// 创建商品
		CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error)
		// 更新商品
		UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error)
		// 更新商品状态
		UpdateProductStatus(ctx context.Context, in *UpdateProductStatusReq, opts ...grpc.CallOption) (*UpdateProductStatusResp, error)
		// 删除商品
		DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductResp, error)
	}

	defaultProductRpc struct {
		cli zrpc.Client
	}
)

func NewProductRpc(cli zrpc.Client) ProductRpc {
	return &defaultProductRpc{
		cli: cli,
	}
}

func (m *defaultProductRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := productrpc.NewProductRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// 根据 ID 查询商品详情
func (m *defaultProductRpc) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	client := productrpc.NewProductRpcClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

// 商品列表（分页，支持 keyword 搜索）
func (m *defaultProductRpc) ListProducts(ctx context.Context, in *ListProductReq, opts ...grpc.CallOption) (*ListProductResp, error) {
	client := productrpc.NewProductRpcClient(m.cli.Conn())
	return client.ListProducts(ctx, in, opts...)
}

// 创建商品
func (m *defaultProductRpc) CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error) {
	client := productrpc.NewProductRpcClient(m.cli.Conn())
	return client.CreateProduct(ctx, in, opts...)
}

// 更新商品
func (m *defaultProductRpc) UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error) {
	client := productrpc.NewProductRpcClient(m.cli.Conn())
	return client.UpdateProduct(ctx, in, opts...)
}

// 更新商品状态
func (m *defaultProductRpc) UpdateProductStatus(ctx context.Context, in *UpdateProductStatusReq, opts ...grpc.CallOption) (*UpdateProductStatusResp, error) {
	client := productrpc.NewProductRpcClient(m.cli.Conn())
	return client.UpdateProductStatus(ctx, in, opts...)
}

// 删除商品
func (m *defaultProductRpc) DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductResp, error) {
	client := productrpc.NewProductRpcClient(m.cli.Conn())
	return client.DeleteProduct(ctx, in, opts...)
}
